# Generated by Django 4.2.6 on 2026-04-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
